server:
  port: 8080

spring:
  application:
    name: student-management-system

  jackson:
    default-property-inclusion: non_default

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://student-management-system.crruakemgggf.us-east-1.rds.amazonaws.com:3306/student_management_system?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: admin
    password: password123$
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

redis:
  host: redis-16989.c14.us-east-1-3.ec2.cloud.redislabs.com
  port: 16989
  password: EqEd3t4jnqQfHw3BV8QnWT2fMs3XvNZQ
  database: 0
  timeout: 1000
  timeToLive: 15
