server:
  port: 8080

spring:
  application:
    name: student-management-system

  jackson:
    default-property-inclusion: non_null


  datasource:
    url: jdbc:mysql://bt9bdm7m5sa6rvrx4xwg-mysql.services.clever-cloud.com:3306/bt9bdm7m5sa6rvrx4xwg?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: un6oimk8htyqwlxj
    password: RuaDytTQck6mKu00TKd1
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

redis:
  host: bccmlkrseikcvx2rv2ax-redis.services.clever-cloud.com
  port: 3366
  password: H9202MBbzvIikK73Rek
  database: 0
  timeout: 1000
  timeToLive: 15
